// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnqyytiduuoeurrpquch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ucXl5dGlkdXVvZXVycnBxdWNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NzE1OTMsImV4cCI6MjA2MTA0NzU5M30.0x0RcPENC6fZuvyCKfzhBoGxj_UOUwTeGJiekLX3AeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);